export const COMMON_LABELS = {
  SAVE: 'Kaydet',
  DELETE: 'Sil',
  CANCEL: 'Vazgeç',
  ADD: 'Ekle',
  EDIT: 'Düzenle',
  REMOVE: 'Kaldır',
  UPDATE: 'Güncelle',
  CLOSE: 'Kapat',
  CONFIRM: 'Onayla',
  DESCRIPTION: 'Açıklama',
  NOTES: 'Notlar',
  DETAILS: 'Detaylar',
  INFORMATION: 'Bilgi',
  SEARCH: 'Ara',
  FILTER: 'Filtrele',
  EXPORT: 'Dışa Aktar',
  IMPORT: 'İçe Aktar',
  STATUS: 'Durum',
} as const;
