export type AcademicRecord = {
  id: string;
  studentId: string;
  term: string;
  gpa?: number;
  notes?: string;
};

export type BehaviorIncident = {
  id: string;
  studentId: string;
  incidentDate: string;
  incidentTime: string;
  location: string;
  behaviorType: string;
  behaviorCategory: string;
  description: string;
  antecedent?: string;
  consequence?: string;
  duration?: number;
  intensity?: string;
  frequency?: string;
  witnessedBy?: string;
  othersInvolved?: string;
  interventionUsed?: string;
  interventionEffectiveness?: string;
  parentNotified: boolean;
  parentNotificationMethod?: string;
  parentResponse?: string;
  followUpRequired: boolean;
  followUpDate?: string;
  followUpNotes?: string;
  adminNotified: boolean;
  consequenceGiven?: string;
  supportProvided?: string;
  triggerAnalysis?: string;
  patternNotes?: string;
  positiveAlternative?: string;
  status: string;
  recordedBy: string;
  notes?: string;
};

export type ExamResult = {
  id: string;
  studentId: string;
  examType: string;
  examName: string;
  examDate: string;
  examProvider?: string;
  totalScore?: number;
  percentileRank?: number;
  turkishScore?: number;
  mathScore?: number;
  scienceScore?: number;
  socialScore?: number;
  foreignLanguageScore?: number;
  turkishNet?: number;
  mathNet?: number;
  scienceNet?: number;
  socialNet?: number;
  foreignLanguageNet?: number;
  totalNet?: number;
  correctAnswers?: number;
  wrongAnswers?: number;
  emptyAnswers?: number;
  totalQuestions?: number;
  subjectBreakdown?: any;
  topicAnalysis?: any;
  strengthAreas?: string[];
  weaknessAreas?: string[];
  improvementSuggestions?: string;
  comparedToGoal?: string;
  comparedToPrevious?: string;
  comparedToClassAverage?: number;
  schoolRank?: number;
  classRank?: number;
  isOfficial: boolean;
  certificateUrl?: string;
  answerKeyUrl?: string;
  detailedReportUrl?: string;
  goalsMet: boolean;
  parentNotified: boolean;
  counselorNotes?: string;
  actionPlan?: string;
  notes?: string;
};
